[package]

name = "dttp"
version = "0.3.0"
authors = ["kurotetsuka <kurotetsuka@gmail.com>"]

[dependencies]
gpgme = "*"
rand = "^0.3"
regex = "^0.1"
rustc-serialize = "^0.3"
#rust-crypto = "*"
serde = "^0.4"
time = "^0.1"
