[package]

name = "dttp"
version = "0.1.0"
authors = ["kurotetsuka <kurotetsuka@gmail.com>"]

[dependencies]
arcmutex = "^0.1"
regex = "^0.1"
time = "^0.1"
rand = "^0.3"
rustc-serialize = "^0.3"
#rust-crypto = "*"
