[package]

name = "dttp"
version = "0.3.0"
authors = ["kurotetsuka <kurotetsuka@gmail.com>"]

[dependencies]
arcmutex = "^0.2"
gpgme = "^0.4"
peg = "^0.3"
rand = "^0.3"
regex = "^0.1"
rustc-serialize = "^0.3"
#rust-crypto = "*"
serde = "^0.7"
serde_json = "^0.7"
serde_macros = "^0.7"
time = "^0.1"
