[package]

name = "dttp"
version = "0.3.0"
authors = ["kurotetsuka <kurotetsuka@gmail.com>"]

[dependencies]
arcmutex = "^0.2"
gpgme = "^0.4"
rand = "^0.3"
regex = "^0.1"
rustc-serialize = "^0.3"
#rust-crypto = "*"
time = "^0.1"
