[package]

name = "dttp"
version = "0.0.1"
authors = ["kurotetsuka <kurotetsuka@gmail.com>"]

[dependencies]
regex = "^0.1.10"
time = "^0.1.9"
rand = "^0.2"
rustc-serialize = "^0.2"
#rust-crypto = "*"
